# Visualizer Configuration
name: DSA Visualizer
description: Interactive visualization of data structures and algorithms
version: 1.0.0

# UI Settings
ui:
  theme: dark
  colors:
    primary: indigo
    secondary: gray
    background: 
      from: gray-900
      via: gray-800
      to: black

# Data Structures Configuration
dataStructures:
  - id: array
    name: Array
    icon: Grid
    color: from-blue-500 to-cyan-500
    description: Visualize searching and sorting algorithms
    difficulty: Beginner
    algorithms: 
      - Linear Search
      - Binary Search 
      - Bubble Sort
      - Quick Sort
      - Merge Sort

  - id: stack
    name: Stack
    icon: Box
    color: from-amber-500 to-orange-500
    description: Visualize LIFO operations like push and pop
    difficulty: Beginner
    algorithms:
      - Push
      - Pop
      - Peek
      - Is Empty
      - Is Full

  - id: queue
    name: Queue
    icon: Send
    color: from-green-500 to-teal-500
    description: Visualize FIFO operations like enqueue and dequeue
    difficulty: Beginner
    algorithms:
      - Enqueue
      - Dequeue
      - Peek
      - Is Empty
      - Is Full

  - id: linked-list
    name: Linked List
    icon: Link2
    color: from-purple-500 to-pink-500
    description: Visualize singly, doubly and circular linked lists
    difficulty: Intermediate
    algorithms:
      - Insert
      - Delete
      - Search
      - Reverse
      - Traverse

  - id: tree
    name: Tree
    icon: TreeDeciduous
    color: from-indigo-500 to-blue-500
    description: Visualize binary trees, BST, and traversal algorithms
    difficulty: Intermediate
    algorithms:
      - Insert
      - Delete
      - Search
      - Traversals
      - Balancing

  - id: graph
    name: Graph
    icon: Share2
    color: from-red-500 to-pink-500
    description: Visualize graph algorithms like BFS, DFS, and Dijkstra
    difficulty: Advanced
    algorithms:
      - BFS
      - DFS
      - Dijkstra
      - Prim's
      - Topological Sort

# Stats Configuration
stats:
  - label: Data Structures
    value: "6"
    icon: Grid

  - label: Algorithms
    value: "30+"
    icon: Code

  - label: Interactive Visualizations
    value: "50+"
    icon: Sparkles

  - label: Happy Learners
    value: "1K+"
    icon: Users

# Navigation Items
navigation:
  - name: GitHub
    icon: Github
    url: https://github.com

  - name: Tutorials
    icon: BookOpen
    url: /tutorials

# Text Content
content:
  title: |
    Master <gradient>Data Structures</gradient> & Algorithms
  subtitle: Interactive visualizations that bring computer science concepts to life. Learn through animation and step-by-step execution.
  ctaPrimary: Start Exploring
  ctaSecondary: View Tutorials
  exploreSectionTitle: Explore <gradient>Data Structures</gradient>
  footerText: Built with React and Tailwind CSS • Designed for computer science education

# Animation Settings
animations:
  headerDelay: 0
  cardStagger: 100
  hoverEffects: true